import React,{useState,useRef} from 'react';
import {Upload,ArrowLeft,Check,FileText,Download} from 'lucide-react';
import {paths} from './routing';
import {LocalLink} from './WorkspacePages';
import {parseContactCSV,inferMapping,reviewContactRows,contactFields} from './contactImportData';
export default function ContactImport({go,contacts,onImport}){
 const [pasted,setPasted]=useState(''),[file,setFile]=useState(null),[mapping,setMapping]=useState({}),[error,setError]=useState(''),[stage,setStage]=useState('file'),[result,setResult]=useState(null),[loading,setLoading]=useState(false);const input=useRef(null);
 async function readFile(file){setError('');if(!file)return;if(file.size>2*1024*1024){setError('Choose a CSV smaller than 2 MB.');return}setLoading(true);try{const parsed=parseContactCSV(await file.text());setFile({...parsed,name:file.name});setMapping(inferMapping(parsed.headers));setStage('map')}catch(e){setError(e.message)}finally{setLoading(false);if(input.current)input.current.value=''}}
 function template(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['Full name,Job title,Company,Email,Location,Opportunity keywords\n'],{type:'text/csv'}));a.download='salesplay-contact-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 const review=file?reviewContactRows(file.rows,mapping,contacts):null;
 function finish(){const rows=review.valid.map(({row,...p})=>({...p,id:'imported-'+crypto.randomUUID()}));const saved=onImport(rows);setResult({count:rows.length,saved});setStage('done')}
 return <div className="contact-import"><LocalLink className="text-button back-link" to={paths.contacts} go={go}><ArrowLeft size={16}/>People at 3M</LocalLink><div className="page-heading"><div><h1>Upload contacts</h1><p>Bring your relationships into the 3M workspace.</p></div></div><ol className="import-steps" aria-label="Import progress">{['Choose file','Map columns','Review & import'].map((label,i)=><li key={label} aria-current={(['file','map','review'].indexOf(stage)===i)?'step':undefined}>{stage==='done'?<Check size={15}/>:<span>{i+1}</span>}{label}</li>)}</ol>{error&&<p className="import-error" role="alert">{error}</p>}
 {stage==='file'&&<section className="import-file"><Upload size={28}/><h2>Start with a contact list</h2><p>Upload a CSV for 3M. Only a full name is required; add roles, email addresses, locations, and keywords to make opportunity searches more useful.</p><label className="button primary upload-label">{loading?'Reading file…':'Choose CSV file'}<input ref={input} type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" aria-label="Choose contacts CSV" disabled={loading} onChange={e=>readFile(e.target.files[0])}/></label><span className="import-limit">Up to 500 contacts · 2 MB</span><button className="text-button" onClick={template}><Download size={16}/>Download column template</button><details className="paste-csv"><summary>Or paste a CSV list</summary><label>Include the header row<textarea aria-label="Paste contact CSV" value={pasted} onChange={e=>setPasted(e.target.value)} placeholder="Full name,Job title,Company,Email"/></label><button className="button" disabled={!pasted.trim()} onClick={()=>readFile({name:'Pasted contact list',size:new Blob([pasted]).size,text:async()=>pasted})}>Use pasted CSV</button></details><p className="import-local">Files are read locally. Imported contacts stay in this browser; nothing is sent to a server.</p></section>}
 {stage==='map'&&<section className="import-paper"><div className="section-heading"><h2>Match your columns</h2><span>{file.name} · {file.rows.length} rows</span></div><p>Check the detected columns. Contacts without a company are assigned to 3M.</p><div className="mapping-list">{contactFields.map(([key,label])=><label key={key}><span>{label}{key==='name'?' *':''}</span><select aria-label={'Map '+label} value={mapping[key]} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="-1">{key==='name'?'Select a column':'Not provided'}</option>{file.headers.map((h,i)=><option key={i} value={String(i)}>{h||'Column '+(i+1)}</option>)}</select><small>{mapping[key]!=='-1'?file.rows[0][Number(mapping[key])]||'Empty in first row':'—'}</small></label>)}</div><div className="import-actions"><button className="button" onClick={()=>{setStage('file');setFile(null)}}>Choose another file</button><button className="button primary" disabled={mapping.name==='-1'} onClick={()=>setStage('review')}>Review contacts</button></div></section>}
 {stage==='review'&&<section className="import-paper"><h2>{review.valid.length} {review.valid.length===1?'contact':'contacts'} ready to import</h2><p>{review.issues.length?review.issues.length+' rows will be skipped. Review the reasons below.':'All rows passed validation.'} Importing does not create verified opportunity links.</p>{review.valid.length>0&&<div className="table-scroll"><table className="import-preview"><thead><tr><th scope="col">Name</th><th scope="col">Role</th><th scope="col">Email</th><th scope="col">Keywords</th></tr></thead><tbody>{review.valid.slice(0,20).map(p=><tr key={p.row}><td>{p.name}</td><td>{p.title}</td><td>{p.email||'—'}</td><td>{p.keywords||'—'}</td></tr>)}</tbody></table></div>}{review.valid.length>20&&<p>Showing the first 20 of {review.valid.length} valid contacts.</p>}{review.issues.length>0&&<details className="import-issues" open={!review.valid.length}><summary>{review.issues.length} skipped rows</summary><ul>{review.issues.map(p=><li key={p.row}><strong>Row {p.row} · {p.name}</strong><span>{p.reason}</span></li>)}</ul></details>}<div className="import-actions"><button className="button" onClick={()=>setStage('map')}>Back to columns</button><button className="button primary" disabled={!review.valid.length} onClick={finish}><Check size={16}/>Import {review.valid.length} {review.valid.length===1?'contact':'contacts'}</button></div></section>}
 {stage==='done'&&<section className="import-file"><Check size={30}/><h2>{result.count} {result.count===1?'contact':'contacts'} imported</h2><p>{result.saved?'Saved in this browser. Open a profile to search captured opportunities and prepare your next conversation.':'Browser storage is unavailable. Your contacts are available for this session only.'}</p><LocalLink className="button primary" to={paths.contacts+'?source=uploaded'} go={go}>View uploaded contacts</LocalLink></section>}
 </div>
}
