import React,{useState} from 'react';
import {Search,MessageSquare,ArrowUpRight,Clock3} from 'lucide-react';
import {LocalLink} from './WorkspacePages';
import {conversationUrl} from './conversations';
function dateGroup(timestamp){const today=new Date();today.setHours(0,0,0,0);const yesterday=new Date(today);yesterday.setDate(yesterday.getDate()-1);return timestamp>=today.getTime()?'Today':timestamp>=yesterday.getTime()?'Yesterday':'Earlier'}
export default function ConversationHistory({sessions,activeId,go,storageError}){
 const [search,setSearch]=useState('');const visible=sessions.filter(c=>(c.title+' '+c.scopeLabel+' '+c.messages.map(m=>m.text).join(' ')).toLowerCase().includes(search.toLowerCase()));
 return <section className="conversation-history" aria-label="Recent interactions"><div className="history-heading"><h2>Recent interactions</h2><span>{sessions.length}</span></div><p className="history-note">Pick up where you left off.</p>{sessions.length>0&&<label className="history-search"><Search size={16}/><input aria-label="Search recent interactions" placeholder="Search conversations…" value={search} onChange={e=>setSearch(e.target.value)}/></label>}{!visible.length?<div className="history-empty"><Clock3 size={23}/><h3>{search?'No matching conversations':'Your conversations start here'}</h3><p>{search?'Try another keyword or clear your search.':'Ask a question and it will be saved here automatically.'}</p>{search&&<button className="text-button" onClick={()=>setSearch('')}>Clear search</button>}</div>:['Today','Yesterday','Earlier'].map(group=>{const items=visible.filter(c=>dateGroup(c.updatedAt)===group);return items.length>0&&<div className="history-group" key={group}><h3>{group}</h3>{items.map(c=><LocalLink className={'history-item '+(activeId===c.id?'current':'')} to={conversationUrl(c)} go={go} key={c.id} aria-current={activeId===c.id?'page':undefined}><MessageSquare size={16}/><span><strong>{c.title}</strong><small>{c.scopeLabel}</small><span className="history-item-meta">{c.messages.filter(m=>m.role==='user').length} {c.messages.filter(m=>m.role==='user').length===1?'question':'questions'}<time dateTime={new Date(c.updatedAt).toISOString()}>{new Date(c.updatedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></span></span><ArrowUpRight size={14}/></LocalLink>)}</div>})}<p className="history-storage" role={storageError?'status':undefined}>{storageError?'Browser storage is unavailable. History is kept for this session only.':'Latest 50 conversations · Saved in this browser'}</p></section>
}
