export const liveBase = 'https://salesplay.marketsandmarkets.com/account_details/6a5635f31a6b100b5d6a4f8e/3M%20Company/LANXESS%20Aktiengesellschaft';
export const people = [
 {name:'Ian Nicacio',title:'Global Director, Business Supply Chain & Manufacturing. Fall Protection & SCBA',initials:'IN',url:'https://linkedin.com/in/ian-nicacio-a7084733'},
 {name:'Janna Burgstahler',title:'Director, Global Business Supply Chain Leader',initials:'JB',url:'https://linkedin.com/in/jmburgstahler'},
 {name:'David Groppel',title:'Director, Global Supply Chain',initials:'DG',url:'https://linkedin.com/in/david-groppel-a315188'}
];
export const opportunities = [
 {id:'6a902f6fb63ea5aa30bc0b31',title:'LEVAGARD / DISFLAMOLL phosphate ester flame retardants for 3M New Ulm electrical cable accessories',short:'New Ulm electrical cable accessories',evidence:'Low',bu:'Safety and Industrial',seller:'Polymer Additives',region:'United States',products:['LEVAGARD','DISFLAMOLL'],contacts:22,status:'review',goal:'Identify one New Ulm cable-accessory formulation tied to the June 2026 production increase, confirm the polymer and flame-retardant system plus whether alternate-source qualification is allowed, and secure a technical screening conversation only if phosphate-ester relevance is confirmed.',people,
 evidenceItems:[
 {title:'A production constraint with a measurable outcome',text:'3M publicly identified New Ulm as a capacity-constrained electrical cable-accessories plant, said a multi-week debottlenecking effort drove record June 2026 production, and tied that effort to $13 million of incremental revenue.',source:'Q2 2026 earnings transcript',url:'https://d1io3yog0oux5.cloudfront.net/_d547424da86c14743ef8f59f60172ecf/3m/db/3222/31004/webcast_transcript/MMM-USQ_Transcript_2026-07-21.pdf'},
 {title:'Growth in Electrical Markets',text:'3M reported Q2 2026 Electrical Markets sales of $391 million versus $349 million in Q2 2025, about 12.0% growth, so the New Ulm output increase sits inside a measured growth line rather than a generic market signal.',source:'3M Q2 2026 Form 10-Q',url:'https://investors.3m.com/financials/sec-filings/content/0000066740-26-000246/mmm-20260630.htm'},
 {title:'Material fit still needs validation',text:'Public 3M product information shows relevant cable-accessory products use silicone rubber in some termination kits and EPDM rubber in some splice kits, which means phosphate-ester fit is unconfirmed and must be screened by product and polymer before any product pitch.',source:'3M cable-accessory portfolio',url:'https://www.3m.com/3M/en_US/electrical-construction-maintenance-us/support/cable-accessories/'}],
 fit:[['DISFLAMOLL','Use as the strongest conditional path only after you confirm that the New Ulm formulation uses a phosphate-ester-compatible polymer and an externally supplied flame-retardant system. LANXESS evidence supports wire-and-cable relevance for compatible PVC, TPU, elastomer, thermoset, or rubber-type compounds, but not for completely nonpolar polymers. Position it as a technical comparison route, not as the answer. Pitch conditionally only after polymer, flame-retardant class, and qualification route are confirmed.'],['LEVAGARD','Keep as a secondary conditional path. The supplied context supports LEVAGARD as part of the mapped flame-retardant portfolio, but does not establish a specific grade fit for 3M’s New Ulm formulations or for silicone, EPDM, PVC, TPU, or other matrices in scope. Introduce only if 3M confirms a phosphate-ester route and you can map a specific grade to the required electrical, processing, and qualification criteria.']],
 script:'I saw 3M call out record June 2026 output at New Ulm after debottlenecking in electrical cable accessories, so I wanted to check whether any of the compounds behind that increase use an externally supplied flame-retardant system. We work on phosphate-ester flame-retardant qualification paths for cable compounds, but I do not want to assume fit. Which team owns formulation and material qualification for those New Ulm products?',
 questions:['Which New Ulm cable-accessory product families drove the June 2026 production increase, and what polymer systems do those specific formulations use?','Do any of those formulations use an externally supplied phosphate-ester flame retardant or another additive package where an alternate supplier could be evaluated?','If an alternate material were relevant, what approval path applies at New Ulm: lab screening only, formal qualification, customer approval, or no change allowed because the formulation is fixed?'],
 responses:[['The relevant New Ulm formulations use silicone, EPDM, mineral-filled, halogenated, or inherently flame-retardant systems with no phosphate-ester role.','Stop the LEVAGARD/DISFLAMOLL play for this site and do not pitch product. Ask only whether another cable-accessory formulation at 3M uses a phosphate-ester-compatible system.'],['A relevant formulation uses a phosphate-ester-compatible polymer and 3M is open to reviewing an alternate source.','Secure a technical screening session focused on polymer compatibility, flame and electrical requirements, processing conditions, incumbent benchmark, and qualification steps; then decide whether DISFLAMOLL or LEVAGARD is the better comparison path.'],['A phosphate-ester-compatible formulation exists, but there is an entrenched incumbent or no second-source path.','Shift to qualification mapping. Ask what event would reopen review—capacity expansion, supply-risk mitigation, reformulation, or scheduled sourcing review—and only stay engaged if you can secure criteria for future entry.']],
 next:'Call or email to identify the New Ulm formulation/material-qualification owner and ask for a 20-minute screening conversation focused on which cable-accessory formulations supported the June 2026 output increase and whether any use a phosphate-ester-compatible flame-retardant system.',outcome:'A technical screening meeting with the owner of New Ulm cable-accessory formulations or material qualification.',proceed:'You confirm at least one relevant formulation uses an externally supplied flame-retardant system and 3M will discuss alternate-material qualification.',stop:'You learn the expanded lines use non-relevant polymer systems, no externally supplied flame retardant, or a closed formulation with no alternate-source path.'},
 {id:'pittsboro',title:'Expand Bayferrox and Colortherm Pigments to 3M’s Pittsboro Roofing Granule Plant',short:'Pittsboro roofing granule plant',evidence:'Medium',bu:'Safety and Industrial',products:['Bayferrox','Colortherm'],contacts:20,status:'review',goal:'Identify whether Pittsboro produces color-coated granules → confirm pigment specifications, current supplier status, and approval path → secure a specification review or qualification discussion tied to the three approved sister sites.'},
 {id:'italy-disflamoll',title:'Evaluate DISFLAMOLL for 3M’s Flame-Retardant Vinyl Electrical Tapes in Italy',short:'Flame-retardant electrical tapes in Italy',evidence:'Medium',bu:'Safety and Industrial',products:['DISFLAMOLL'],contacts:8,status:'review',goal:'Identify one Italian vinyl electrical-tape grade in active scope → confirm the incumbent flame-retardant/plasticizer system and approval criteria under NDA → secure agreement to run a side-by-side qualification on that grade.'},
 {id:'italy-mesamoll',title:'MESAMOLL® plasticizer for 3M vinyl electrical tapes sold in Italy',short:'Vinyl electrical tapes sold in Italy',evidence:'Low',bu:'Safety and Industrial',products:['MESAMOLL®'],offeringCount:3,contacts:5,status:'review',goal:'Identify one active EMEA owner for the Temflex or Scotch PVC tape formulations sold in Italy → confirm the incumbent plasticizer requirements, grade scope, and whether qualification is open → secure a technical screening discussion for MESAMOLL® against agreed test criteria.'},
 {id:'france',title:'Evaluate MESAMOLL for 3M’s Flexible PVC Electrical Tape Backings in France',short:'Flexible PVC tape backings in France',evidence:'Medium',bu:'Safety and Industrial',products:['MESAMOLL'],offeringCount:3,contacts:7,status:'review',goal:'Identify the European Temflex PVC backing owner and active qualification path → confirm whether plasticizer selection is open for a defined backing formulation → secure agreement to scope a controlled comparison in the existing formulation.'},
 {id:'6a97e121a8689e0f994637a9',title:'High-purity 1,6-Hexanediol for 3M Woodlands’ optically clear adhesive (OCA) synthesis',short:'Woodlands optically clear adhesives',evidence:'Low',bu:'Transportation and Electronics',products:['1,6-Hexanediol'],offeringCount:2,contacts:13,status:'accepted',goal:'Identify one active Woodlands OCA formulation or raw-material review → confirm whether a purchased diol is used, who owns qualification, and whether specification is still open → secure a technical review to compare current criteria against a possible benchmark material.'},
 {id:'hutchinson',title:'1,6-Hexanediol (Scopeblue mass-balanced) for 3M Hutchinson’s Scotch Tape and acrylic adhesive synthesis',short:'Hutchinson tape and adhesive synthesis',evidence:'Medium',bu:'Safety and Industrial',products:['Scopeblue® 1,6-Hexanediol'],offeringCount:2,contacts:19,status:'accepted',goal:'Identify whether Hutchinson buys merchant 1,6-Hexanediol for tape or adhesive production → confirm the current specification, owner, supplier, volume, and change-control path → secure a technical review to compare the incumbent grade against Scopeblue® 1,6-Hexanediol.'}
];
