import React,{useMemo,useState} from 'react';
import {Search,X,ChevronDown,Check} from 'lucide-react';
import './entity-selector.css';
const normalize=s=>s.trim().toLocaleLowerCase();
export default function EntitySelector({dimension,values,selected,onChange,people=[],compact=false}){
 const [query,setQuery]=useState(''),[limit,setLimit]=useState(compact?8:12),[mode,setMode]=useState('select'),[paste,setPaste]=useState(''),[review,setReview]=useState(null),[selectedQuery,setSelectedQuery]=useState('');
 const filtered=useMemo(()=>values.filter(v=>{const p=people.find(p=>p.name===v);return [v,p?.title||''].join(' ').toLowerCase().includes(query.toLowerCase());}),[values,query,people]);
 const visible=filtered.slice(0,limit);
 function toggle(v){onChange(selected.includes(v)?selected.filter(x=>x!==v):[...selected,v]);}
 function reviewPaste(){const seen=new Set();setReview(paste.split(/[\n,;\t]+/).map(v=>v.trim()).filter(Boolean).map((raw,id)=>{const matches=values.filter(v=>normalize(v)===normalize(raw));const duplicate=seen.has(normalize(raw));seen.add(normalize(raw));const state=duplicate?'Duplicate':matches.length>1?'Ambiguous':matches.length===1?(selected.includes(matches[0])?'Already selected':'Matched'):'Unmatched';return {id,raw,value:matches[0],state,include:state==='Matched'};}));}
 const selectedShown=selected.filter(v=>v.toLowerCase().includes(selectedQuery.toLowerCase()));
 return <div className={'es-selector '+(compact?'es-compact':'')}>
 {!compact&&<div className="es-modes"><button aria-pressed={mode==='select'} onClick={()=>setMode('select')}>Select from account</button><button aria-pressed={mode==='paste'} onClick={()=>setMode('paste')}>Paste a list</button></div>}
 <div className="es-columns"><section className="es-available">{mode==='select'?<><label className="es-search"><Search size={16}/><input aria-label={'Find a '+dimension.toLowerCase()} placeholder={'Find '+dimension.toLowerCase()+'…'} value={query} onChange={e=>{setQuery(e.target.value);setLimit(compact?8:12);}}/>{query&&<button aria-label={'Clear '+dimension+' lookup'} onClick={()=>setQuery('')}><X size={14}/></button>}</label><div className="es-count">{filtered.length} {query?'matching':'available'} · 3M Company</div><div className="es-list" role="group" aria-label={dimension+' choices'}>{visible.map(v=>{const person=people.find(p=>p.name===v);return <label key={v}><input type="checkbox" checked={selected.includes(v)} onChange={()=>toggle(v)}/><span><strong>{v}</strong>{person?.title&&<small>{person.title}</small>}</span></label>})}{!filtered.length&&<p className="es-empty">No {dimension.toLowerCase()} values match this search. Try a different name.</p>}</div>{filtered.length>limit&&<button className="cx-link es-more" onClick={()=>setLimit(n=>n+(compact?8:12))}>Load more<ChevronDown size={14}/></button>}<small className="es-footnote">Showing {visible.length} of {filtered.length}. Selections stay when you search again.</small></>:<div className="es-paste"><label htmlFor={'paste-values-'+dimension}>Paste {dimension.toLowerCase()} names</label><textarea id={'paste-values-'+dimension} rows={7} value={paste} onChange={e=>{setPaste(e.target.value);setReview(null);}} placeholder="One name per line, or separated by commas, semicolons, or tabs."/><p>Review exact matches before adding them. Unmatched or ambiguous entries will not be added automatically.</p><button className="cx-button" disabled={!paste.trim()} onClick={reviewPaste}>Review list</button>{review&&<section className="es-review"><h3>Review {review.length} entries</h3><div className="es-review-list">{review.map(r=><label key={r.id}><input type="checkbox" disabled={r.state!=='Matched'} checked={r.include} onChange={()=>setReview(rs=>rs.map(x=>x.id===r.id?{...x,include:!x.include}:x))}/><span><strong>{r.raw}</strong><small>{r.state}</small></span></label>)}</div><p>{review.filter(r=>r.include).length} matches ready to add. Edit the list to resolve excluded entries.</p><button className="cx-button cx-primary" disabled={!review.some(r=>r.include)} onClick={()=>{onChange([...new Set([...selected,...review.filter(r=>r.include).map(r=>r.value)])]);setReview(null);setPaste('');setMode('select');}}>Add selected matches<Check size={15}/></button></section>}</div>}</section>
 <section className="es-selected" aria-label={'Selected '+dimension.toLowerCase()}><div className="es-selected-heading"><strong>Selected · {selected.length}</strong>{selected.length>0&&<button className="cx-link" onClick={()=>onChange([])}>Clear all</button>}</div>{(selected.length>8||selectedQuery)&&<label className="es-search"><Search size={14}/><input aria-label={'Search selected '+dimension.toLowerCase()} placeholder="Find selected…" value={selectedQuery} onChange={e=>setSelectedQuery(e.target.value)}/></label>}<div className="es-selected-list">{selectedShown.map(v=><button key={v} aria-label={'Remove '+v} onClick={()=>toggle(v)}><span>{v}</span><X size={14}/></button>)}</div>{!selected.length&&<p>Your selections will appear here.</p>}{selected.length>0&&!selectedShown.length&&<p>No selected values match.</p>}</section></div>
 </div>;
}
