import React,{useState,useRef,useEffect} from 'react';
import {Sparkles,Search,ArrowRight,ArrowUp,ArrowUpRight,Users,BriefcaseBusiness,FileText,Radio,ChevronDown,HelpCircle} from 'lucide-react';
import {contacts,documents,LocalLink} from './WorkspacePages';
import research from './research.json';
import {paths} from './routing';
import ThemePicker from './ThemePicker';
import {accountRecords,accountUrl} from './accounts';
export default function GlobalBar({go,ask,askEntity,view,records,current,route,portfolio,openAssistant,contactRecords=contacts}){
 const directory=portfolio&&view!=='home';
 const [mode,setMode]=useState(directory?'search':'ask'),[text,setText]=useState(''),[focused,setFocused]=useState(false);const input=useRef(null),root=useRef(null);
 useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setMode('search');requestAnimationFrame(()=>input.current?.focus());setFocused(true)}if(e.key==='Escape'){setFocused(false);input.current?.blur()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 useEffect(()=>{setFocused(false)},[route.path]);
 useEffect(()=>{setText('');setMode(directory?'search':'ask')},[directory]);
 const q=text.trim().toLowerCase();const results=q?(portfolio?accountRecords.filter(a=>a.name.toLowerCase().includes(q)).slice(0,7).map(a=>({name:a.name,meta:a.sample?'Sample account':a.industry,icon:BriefcaseBusiness,to:accountUrl(a)})):[...contactRecords.filter(p=>(p.name+' '+p.title+' '+p.location).toLowerCase().includes(q)).map(p=>({name:p.name,meta:p.title,icon:Users,to:paths.contacts+'/'+p.id})),...records.filter(o=>(o.title+' '+o.products.join(' ')).toLowerCase().includes(q)).map(o=>({name:o.short,meta:'Opportunity · '+o.evidence+' evidence',icon:BriefcaseBusiness,to:paths.list+'/'+o.id})),...documents.filter(d=>(d.title+' '+d.type).toLowerCase().includes(q)).map(d=>({name:d.title,meta:d.type,icon:FileText,to:paths.documents+'/'+d.id})),...research.signals.filter(s=>s.title.toLowerCase().includes(q)).map(s=>({name:s.title,meta:'Account update · '+s.date,icon:Radio,to:paths.signals+'/'+s.id}))].sort((a,b)=>{const score=r=>r.name.toLowerCase()===q?3:r.name.toLowerCase().split(/\s+/).some(w=>w.startsWith(q))?2:1;return score(b)-score(a)}).slice(0,7)):[];
 function submit(e){e.preventDefault();if(q&&results.length){go(results[0].to);setFocused(false)}}
 return <header className="global-bar"><div className="global-brand"><LocalLink to={paths.home} go={go} aria-label="SalesPlay home">SalesPlay<span>.</span></LocalLink></div><form className={'global-command '+(focused?'has-focus':'')} ref={root} onSubmit={submit} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false)}}>{!directory&&<label className="command-mode"><select aria-label="Top bar mode" value={mode} onChange={e=>{setMode(e.target.value);if(e.target.value==='ask')openAssistant();else requestAnimationFrame(()=>input.current?.focus())}}><option value="ask">Ask SalesPlay</option><option value="search">{portfolio?'Find accounts':'Search account'}</option></select><ChevronDown size={12}/></label>}{!directory&&mode==='ask'?<button type="button" className="ask-workspace-trigger" onClick={openAssistant}><Sparkles size={17}/><span>{view==='home'?'Ask SalesPlay · 3M Company…':'Ask a question about this account…'}</span><ArrowUpRight size={17}/></button>:<><Search size={17}/><input ref={input} value={text} onChange={e=>setText(e.target.value)} onFocus={()=>setFocused(true)} aria-label={portfolio?'Find an account':'Search across the account'} placeholder={portfolio?'Find an account…':'Search people, opportunities, documents…'} autoComplete="off"/><kbd>⌘ K</kbd><button type="submit" className="command-submit" disabled={!q} aria-label="Open first search result"><ArrowRight size={17}/></button></>}{focused&&mode==='search'&&q&&<div className="global-results"><div className="results-label" role="status">{results.length?results.length+(portfolio?' matching accounts':' results in the captured account'):'No matching results'}</div>{results.map(r=><LocalLink to={r.to} go={go} key={r.to}><r.icon size={19}/><span><strong>{r.name}</strong><small>{r.meta}</small></span><ArrowUp size={14}/></LocalLink>)}{!results.length&&<p>{portfolio?'Try a company name, such as 3M.':'Try a name such as Ian, an offering such as MESAMOLL, or “earnings”.'}</p>}</div>}</form><div className="global-tools"><ThemePicker/><LocalLink go={go} to={paths.accounts}>Accounts</LocalLink><LocalLink go={go} to={paths.help} aria-label="Help"><HelpCircle size={18}/></LocalLink><span className="header-avatar" title="Ankur Jain">AJ</span></div></header>
}
