import React,{useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,X,Search,Upload,Sparkles,Star,Clock3,BriefcaseBusiness} from 'lucide-react';
import {LocalLink,Avatar} from './WorkspacePages';
import {paths} from './routing';
import {accountRecords,accountUrl} from './accounts';
import {conversationUrl} from './conversations';
import research from './research.json';
import './home.css';

const recentKey='salesplay-recent-work-v1';
export function useRecentWork(route,records,contacts){
 const [items,setItems]=useState(()=>{try{const v=JSON.parse(localStorage.getItem(recentKey)||'[]');return Array.isArray(v)?v.filter(x=>x&&typeof x.title==='string'&&typeof x.to==='string'&&/^\/accounts\/3m\/(opportunities|contacts)\/[^/?]+$/.test(x.to)&&Number.isFinite(x.at)).slice(0,8):[]}catch{return []}});
 useEffect(()=>{const item=route.view==='detail'?records.find(o=>o.id===route.id):route.view==='contact'?contacts.find(p=>p.id===route.id):null;if(!item)return;const to=(route.view==='detail'?paths.list:paths.contacts)+'/'+item.id;setItems(old=>[{title:item.short||item.name,to,kind:route.view==='detail'?'Opportunity':'Person',at:Date.now()},...old.filter(x=>x.to!==to)].slice(0,8))},[route.view,route.id]);
 useEffect(()=>{try{localStorage.setItem(recentKey,JSON.stringify(items))}catch{}},[items]);
 return items;
}
function dateLabel(value){const [d,m,y]=value.split('/');return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(+y,+m-1,+d)))}
export default function HomeWorkspace({go,records,contacts,preferences,sessions,recentWork,changeStatus,ask}){
 const [status,setStatus]=useState('review'),[query,setQuery]=useState(''),[peopleTab,setPeopleTab]=useState('linked');
 const labels={review:'To review',accepted:'Accepted',rejected:'Rejected'};
 const queue=records.filter(o=>o.status===status&&[o.title,o.bu,...o.products].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 const uploaded=contacts.filter(p=>p.imported);
 const linked=contacts.map(p=>({...p,links:records.filter(o=>o.status!=='rejected'&&o.people?.some(c=>c.name===p.name)&&!p.imported)})).filter(p=>p.links.length).sort((a,b)=>Number(b.links.some(o=>o.status==='accepted'))-Number(a.links.some(o=>o.status==='accepted')));
 const shownPeople=(peopleTab==='uploaded'?uploaded:linked).slice(0,3);
 const recent=[...recentWork,...sessions.map(s=>({title:s.title,to:conversationUrl(s),kind:'AI conversation',at:s.updatedAt})),...preferences.recent.map(r=>{const a=accountRecords.find(a=>a.id===r.id);return a?{title:a.name,to:accountUrl(a),kind:'Account',at:r.at}:null}).filter(Boolean)].sort((a,b)=>b.at-a.at).slice(0,3);
 const accountIds=[...new Set([...preferences.favourites,...preferences.recent.map(r=>r.id),'3m'])].slice(0,4);
 return <div className="home-workspace">
  <header className="home-heading"><div><h1>Find your next opportunity.</h1><p>Your opportunities, relationships, and account intelligence in one place.</p></div><LocalLink className="button" go={go} to={paths.contactsImport}><Upload size={16}/>Upload contacts</LocalLink></header>
  <div className="home-scope"><span className="home-account-mark">3M</span><span><strong>3M Company</strong><span>Research available in this preview</span></span><LocalLink go={go} to={paths.accounts}>Browse all accounts<ArrowRight size={15}/></LocalLink></div>
  {!recent.length&&<div className="home-start"><strong>Make this workspace yours</strong><LocalLink go={go} to={paths.accounts}>Choose your accounts<ArrowRight size={14}/></LocalLink><LocalLink go={go} to={paths.contactsImport}>Bring your contacts<ArrowRight size={14}/></LocalLink><a href="#home-queue">Review your first opportunity<ArrowRight size={14}/></a></div>}
  <div className="home-main-grid"><section className="home-queue" id="home-queue" aria-labelledby="home-queue-title">
   <div className="home-section-heading"><h2 id="home-queue-title">Opportunities to pursue</h2><span>{records.length} captured</span></div>
   <div className="home-queue-tools"><div className="home-state-tabs" aria-label="Opportunity status">{Object.entries(labels).map(([key,label])=><button key={key} aria-pressed={status===key} onClick={()=>setStatus(key)}>{label}<span>{records.filter(o=>o.status===key).length}</span></button>)}</div><label className="home-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search home opportunities" placeholder="Find an opportunity…"/></label></div>
   <div className="home-queue-results" role="status">{query&&`${queue.length} matching ${queue.length===1?'opportunity':'opportunities'}`}</div>
   {queue.map(o=><article className="home-opportunity" key={o.id}><div className="home-opportunity-meta"><span>3M Company</span><span className={'home-evidence '+o.evidence.toLowerCase()}>{o.evidence} evidence</span></div><LocalLink className="home-opportunity-title" go={go} to={paths.list+'/'+o.id}>{o.title}<ArrowUpRight size={17}/></LocalLink><div className="home-opportunity-context">{o.bu}<span aria-hidden="true">·</span>{o.products.join(' / ')}</div><details className="home-next-step"><summary>{o.evidenceItems?'Why now & next step':'Next step'}</summary>{o.evidenceItems&&<p>{o.evidenceItems[0].text}</p>}<p>{o.goal}</p></details><div className="home-row-actions"><LocalLink go={go} to={paths.list+'/'+o.id} className="text-button">Review opportunity<ArrowRight size={15}/></LocalLink><div>{status==='review'?<><button className="home-accept" aria-label={'Accept '+o.short} onClick={()=>changeStatus(o.id,'accepted')}><Check size={16}/>Accept</button><button className="home-reject" aria-label={'Reject '+o.short} onClick={()=>changeStatus(o.id,'rejected')}><X size={16}/>Reject</button></>:<button className="text-button" onClick={()=>changeStatus(o.id,'review')}>Return to review</button>}</div></div></article>)}
   {!queue.length&&<div className="home-empty"><BriefcaseBusiness size={25}/><h3>{query?'No matching opportunities':status==='review'?'You’re through your review queue':'No '+labels[status].toLowerCase()+' opportunities'}</h3><p>{query?'Try a product, location, or business unit.':'Use the status tabs to revisit your decisions.'}</p>{query&&<button className="button" onClick={()=>setQuery('')}>Clear search</button>}</div>}
   <p className="home-caption">Decisions apply to this preview session. No live records are changed.</p>
  </section><aside className="home-support">
   <section className="home-people"><div className="home-section-heading"><h2>People to engage</h2><LocalLink go={go} to={paths.contacts} aria-label="View all people"><ArrowUpRight size={19}/></LocalLink></div><p>Start with a relationship, then explore the opportunity.</p><div className="home-people-tabs"><button aria-pressed={peopleTab==='linked'} onClick={()=>setPeopleTab('linked')}>Linked people</button><button aria-pressed={peopleTab==='uploaded'} onClick={()=>setPeopleTab('uploaded')}>Your uploads <span>{uploaded.length}</span></button></div>{shownPeople.map(p=><div className="home-person" key={p.id}><LocalLink className="home-person-identity" go={go} to={paths.contacts+'/'+p.id}><Avatar person={p}/><span><strong>{p.name}</strong><small>{p.title}</small></span></LocalLink>{p.links?<LocalLink className="home-person-context" go={go} to={paths.list+'/'+p.links[0].id}>{p.links[0].short}<ArrowUpRight size={13}/></LocalLink>:<LocalLink className="home-person-context" go={go} to={paths.contacts+'/'+p.id}>Find opportunities<ArrowRight size={13}/></LocalLink>}</div>)}{!shownPeople.length&&<div className="home-empty-small"><p>{peopleTab==='uploaded'?'Upload your contacts to explore opportunities together.':'No named contacts are captured for these active opportunities. Explore the directory to find a starting point.'}</p><LocalLink className="text-button" go={go} to={peopleTab==='uploaded'?paths.contactsImport:paths.contacts}>{peopleTab==='uploaded'?'Upload contacts':'Explore people'}<ArrowRight size={15}/></LocalLink></div>}<p className="home-caption">{peopleTab==='linked'?'Captured relationships · Confirm ownership before outreach.':'Uploaded contacts do not have verified opportunity links.'}</p></section>
   <section className="home-resume"><div className="home-section-heading"><h2>Continue your work</h2><Clock3 size={18}/></div>{recent.length?recent.map(r=><LocalLink key={r.to} className="home-resume-item" go={go} to={r.to}><span><small>{r.kind}</small><strong>{r.title}</strong></span><ArrowUpRight size={16}/></LocalLink>):<p className="home-caption">Your recently opened accounts, people, opportunities, and AI conversations will appear here.</p>}</section>
   <section className="home-ai"><Sparkles size={21}/><h2>A clearer next move.</h2><p>Use Ask SalesPlay to explore the evidence and prepare your next conversation.</p><button onClick={()=>ask(null,'Which opportunities at 3M should I prioritise, and what should I validate first?')}>Help me prioritise<ArrowUpRight size={16}/></button><span>AI context: 3M Company</span></section>
  </aside></div>
  <div className="home-bottom-grid"><section className="home-signals"><div className="home-section-heading"><h2>What changed</h2><LocalLink className="text-button" go={go} to={paths.signals}>All signals<ArrowRight size={15}/></LocalLink></div><p className="home-caption">Latest captured updates from 3M. Opportunity relevance still needs review.</p>{research.signals.slice(0,3).map(s=><LocalLink className="home-signal" go={go} to={paths.signals+'/'+s.id} key={s.id}><span><small>{dateLabel(s.date)} · {s.category}</small><strong>{s.title}</strong></span><ArrowUpRight size={16}/></LocalLink>)}</section><section className="home-accounts"><div className="home-section-heading"><h2>Your accounts</h2><LocalLink className="text-button" go={go} to={paths.accounts}>All accounts<ArrowRight size={15}/></LocalLink></div><p className="home-caption">Favourites first, followed by recently opened accounts.</p>{accountIds.map(id=>{const a=accountRecords.find(a=>a.id===id);return <div className="home-account" key={id}><LocalLink go={go} to={accountUrl(a)}><span className={'account-monogram '+(!a.sample?'is-3m':'')}>{a.initials}</span><span><strong>{a.name}</strong><small>{a.sample?'Sample account':'Captured research'}</small></span></LocalLink><button className="icon-button" aria-label={(preferences.favourites.includes(id)?'Remove ':'Add ')+a.name+(preferences.favourites.includes(id)?' from favourites':' to favourites')} aria-pressed={preferences.favourites.includes(id)} onClick={()=>preferences.toggleFavourite(id)}><Star size={17} fill={preferences.favourites.includes(id)?'currentColor':'none'}/></button></div>})}</section></div>
 </div>;
}
