import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ArrowRight,ArrowUp,ArrowUpRight,Search,SlidersHorizontal,ChevronDown,ChevronRight,Check,CheckCheck,X,Plus,Sparkles,BriefcaseBusiness,Radio,Users,Building2,FileText,ChartNoAxesCombined,Home,Star,PanelLeftClose,PanelLeft,Bookmark,Globe,ExternalLink,MessageSquare,Send,Copy,Download,Info,Ellipsis,ShieldCheck,Clock3,Menu,ChevronsUpDown,Paperclip,BookOpen,RotateCcw} from 'lucide-react';
import {opportunities,people} from './data';
import OpportunityConcepts from './OpportunityConcepts';
import CombinedConcepts from './CombinedConcepts';
import './styles.css';
import './premium.css';
import './themes.css';
import './workspace.css';
import './accounts.css';
import './refinements.css';
import './people-research.css';
import './primary-opportunities.css';
import {loadImportedContacts,importKey} from './contactImportData';
import ConversationHistory from './ConversationHistory';
import {useConversations} from './conversations';
import AccountDirectory,{useAccountPreferences} from './AccountDirectory';
import HomeWorkspace,{useRecentWork} from './HomeWorkspace';
import {accountRecords,portfolioViews} from './accounts';
import GlobalBar from './GlobalBar';
import WorkspacePages,{PeoplePanel,LocalLink,contacts,documents,Avatar} from './WorkspacePages';
import {useRoute,paths,slug,pageNames} from './routing';

const iconSize=18;
const Icon=({as:Component,...p})=><Component size={iconSize} strokeWidth={1.7} {...p}/>;
function Evidence({value}){return <span className={'evidence '+value.toLowerCase()}><span className="evidence-bars"><i/><i/><i/></span>{value} evidence</span>}
function App(){
 const [route,go]=useRoute();
 const view=route.view==='detail'&&!opportunities.some(o=>o.id===route.id)?'notfound':route.view;
 const [selected,setSelected]=useState(opportunities.find(o=>o.id===route.id)||opportunities[0]),[status,setStatus]=useState('review'),[query,setQuery]=useState(''),[evidence,setEvidence]=useState('All evidence'),[bu,setBu]=useState('All business units'),[sort,setSort]=useState('Original order'),[filters,setFilters]=useState(false),[bookmarks,setBookmarks]=useState(()=>opportunities.slice(0,3).map(o=>o.id)),[savedOnly,setSavedOnly]=useState(false),[records,setRecords]=useState(opportunities),[sidebar,setSidebar]=useState(true),[research,setResearch]=useState(true),[toast,setToast]=useState(null),[detailTab,setDetailTab]=useState('Overview'),[contactPanel,setContactPanel]=useState(null),[aiContext,setAiContext]=useState(opportunities.find(o=>o.id===route.params.get('opportunity'))||null),[draft,setDraft]=useState(''),[scopeOpen,setScopeOpen]=useState(false);
 const capturedRecords=records.filter(o=>!o.imported);
 const [opportunityNavigation,setOpportunityNavigation]=useState(0);
 const opportunityScope=route.params.get('view')==='explore'?'All opportunities':route.params.get('view')==='my'?'My opportunities':'Recommended';
 const opportunityUrl=scope=>paths.list+(scope==='All opportunities'?'?view=explore':scope==='My opportunities'?'?view=my':'');
 const [savedContacts,setSavedContacts]=useState([]);
 const [importedContacts,setImportedContacts]=useState(()=>{try{return loadImportedContacts(localStorage)}catch{return []}});
 const contactRecords=[...contacts,...importedContacts];
 function importContacts(rows){const next=[...importedContacts,...rows];setImportedContacts(next);try{localStorage.setItem(importKey,JSON.stringify(next));return true}catch{return false}}
 const [library,setLibrary]=useState(false);
 const chats=useConversations(route,go),{messages,busy}=chats;
 const [historyOpen,setHistoryOpen]=useState(false);
 const composerRef=useRef(null);
 useEffect(()=>{if(view==='ai')requestAnimationFrame(()=>composerRef.current?.focus())},[view,route.params.toString()]);
 const portfolio=portfolioViews.includes(view);
 const preferences=useAccountPreferences(route);
 const recentWork=useRecentWork(route,records,contactRecords);
 const sampleAccount=accountRecords.find(a=>a.id===route.id);

 const entityContext=route.params.has('contact')?{type:'contact',item:contactRecords.find(p=>p.id===route.params.get('contact'))}:route.params.has('document')?{type:'document',item:documents.find(d=>d.id===route.params.get('document'))}:null;
 function setView(next){go(next==='detail'?paths.list+'/'+selected.id:paths[next]||paths.list)}
 function askEntity(type,id,prompt){setHistoryOpen(false);setAiContext(null);setDraft(prompt||'');go(paths.ai+'?'+type+'='+encodeURIComponent(id));if(innerWidth<1050)setSidebar(false)}
 useEffect(()=>{setFilters(false);setContactPanel(null);if(innerWidth<1050)setSidebar(false);if(['overview','documents','document','investor','earnings','financials','competitors'].includes(route.view))setResearch(true);if(route.view==='detail'){const o=opportunities.find(o=>o.id===route.id);if(o)setSelected(o);setDetailTab(route.tab)}if(route.view==='ai')setAiContext(opportunities.find(o=>o.id===route.params.get('opportunity'))||null);document.title=(pageNames[route.view]||'SalesPlay')+(portfolio?' · SalesPlay':' · 3M · SalesPlay')},[route.path,route.params.toString()]);
 const searchRef=useRef(null),chatBottom=useRef(null),listScroll=useRef(0),drawerRef=useRef(null);
 useEffect(()=>{if(view==='list')requestAnimationFrame(()=>window.scrollTo(0,listScroll.current))},[view]);
 useEffect(()=>{if(!contactPanel)return;const previous=document.activeElement;const root=drawerRef.current;const controls=()=>[...root.querySelectorAll('button,a[href]')];controls()[0]?.focus();const trap=e=>{if(e.key==='Tab'){const items=controls(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};root.addEventListener('keydown',trap);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{root.removeEventListener('keydown',trap);document.body.style.overflow=old;previous?.focus()}},[contactPanel]);
 const current=records.find(o=>o.id===(view==='detail'?route.id:selected.id))||selected;
 useEffect(()=>{const handle=e=>{if(e.key==='Escape'){setContactPanel(null);setFilters(false);setScopeOpen(false);if(innerWidth<1050)setSidebar(false)}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle)},[]);
 useEffect(()=>{if(innerWidth<1050)setSidebar(false)},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),4500);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{chatBottom.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages,busy]);
 function notify(message){setToast({message})}
 function openDetail(o){if(view==='list')listScroll.current=window.scrollY;setSelected(o);setDetailTab('Overview');go(paths.list+'/'+o.id);window.scrollTo(0,0)}
 function ask(o=null,prompt=null){setHistoryOpen(false);if(view==='list')listScroll.current=window.scrollY;setAiContext(o);go(paths.ai+(o?'?opportunity='+o.id:''));setDraft(prompt||'');if(innerWidth<1050)setSidebar(false);window.scrollTo(0,0)}
 function changeStatus(id,next){let before=records.find(o=>o.id===id).status;setRecords(rs=>rs.map(o=>o.id===id?{...o,status:next}:o));setToast({message:next==='accepted'?'Opportunity accepted in this prototype.':next==='rejected'?'Opportunity moved to rejected.':'Opportunity returned to review.',undo:()=>setRecords(rs=>rs.map(o=>o.id===id?{...o,status:before}:o))})}
 function toggleBookmark(id){setBookmarks(b=>b.includes(id)?b.filter(x=>x!==id):[...b,id])}
 const visible=records.filter(o=>o.status===status&&(!savedOnly||bookmarks.includes(o.id))&&(evidence==='All evidence'||o.evidence===evidence)&&(bu==='All business units'||o.bu===bu)&&[o.title,o.goal,o.bu,...o.products,...(o.people||[]).map(p=>p.name+' '+p.title)].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='Most contacts'?b.contacts-a.contacts:sort==='Evidence strength'?a.evidence.localeCompare(b.evidence)*-1:0);
 function newChat(){const params=new URLSearchParams(route.params);params.delete('chat');go(paths.ai+(params.size?'?'+params.toString():''));setDraft('');setHistoryOpen(false);requestAnimationFrame(()=>composerRef.current?.focus())}
 function send(prompt=draft){if(!prompt.trim()||busy)return;const scopeLabel=entityContext?.item?(entityContext.item.name||entityContext.item.title):aiContext?.short||'3M Company · Account';if(chats.send(prompt.trim(),scopeLabel))setDraft('')}
 function openAssistant(){if(view==='ai'){setHistoryOpen(false);requestAnimationFrame(()=>composerRef.current?.focus());return}if(view==='contact')askEntity('contact',route.id);else if(['document','investor','earnings'].includes(view))askEntity('document',view==='investor'?documents[1].id:view==='earnings'?documents[2].id:route.id);else ask(view==='detail'?current:null)}
 async function copy(text){try{await navigator.clipboard.writeText(text);notify('Copied to clipboard.')}catch{notify('Clipboard is unavailable. Select and copy the text directly.')}}
 function download(){let content=current.title+'\n\nGoal\n'+current.goal;if(current.evidenceItems)content+='\n\nWhy call now\n'+current.evidenceItems.map(i=>i.text+'\n'+i.url).join('\n\n')+'\n\nNext move\n'+current.next;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/plain'}));a.download='salesplay-opportunity.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 const statusLabels={review:'To review',accepted:'Accepted',rejected:'Rejected'};
 function navLink(label,icon,key,sub){const active=view===key||(key==='contacts'&&['contact','contactsImport'].includes(view))||(key==='documents'&&view==='document')||(key==='signals'&&view==='signal')||(key==='accounts'&&view==='accountPreview');return <LocalLink className={'nav-link '+(sub?'nav-sub ':'')+(active?'active':'')} aria-current={active?'page':undefined} to={paths[key]} go={go}>{icon&&<Icon as={icon}/>}<span>{label}</span></LocalLink>}
 return <div className={'app '+(!sidebar?'rail-closed':'')}>
 <a className="skip-link" href="#main">Skip to content</a><GlobalBar go={go} ask={ask} askEntity={askEntity} view={view} records={capturedRecords} current={current} route={route} portfolio={portfolio} contactRecords={contactRecords} openAssistant={openAssistant}/>
 {sidebar&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
 <aside className="sidebar" id="workspace-navigation">
 {portfolio?<><div className="portfolio-identity"><strong>Your workspace</strong><span>LANXESS Aktiengesellschaft</span></div><nav aria-label="Workspace navigation">{navLink('Home',Home,'home')}{navLink('Recently used',Clock3,'recent')}{navLink('Favourites',Star,'favourites')}{navLink('All accounts',Building2,'accounts')}</nav></>:<>
  <LocalLink className="all-accounts" to={paths.accounts} go={go}><Icon as={ArrowLeft} size={14}/> All accounts</LocalLink>
  <div className="account-switch"><div className="company-logo">3M</div><div><strong>3M Company</strong><span>Account workspace</span></div></div>
  <nav aria-label="Account navigation">
   <p className="nav-label">DISCOVER</p>
   <button className={'nav-link '+(['list','detail'].includes(view)?'active':'')} onClick={()=>{setView('list');if(innerWidth<1050)setSidebar(false)}}><Icon as={BriefcaseBusiness}/><span>Opportunities</span><span className="nav-count">{capturedRecords.filter(o=>o.status==='review').length}</span></button>
   <div className="opportunity-navigation" aria-label="Opportunity views">{['Recommended','All opportunities','My opportunities'].map(scope=><LocalLink key={scope} to={opportunityUrl(scope)} go={to=>{setOpportunityNavigation(n=>n+1);go(to)}} className={'nav-link nav-sub '+(view==='list'&&opportunityScope===scope?'active':'')} aria-current={view==='list'&&opportunityScope===scope?'page':undefined}>{scope==='All opportunities'?'Explore':scope==='My opportunities'?'My Opportunities':scope}</LocalLink>)}</div>
   {navLink('Signals',Radio,'signals')}
   <p className="nav-label">ENGAGE</p>{navLink('People',Users,'contacts')}
   <button className={'nav-link ai-nav '+(view==='ai'?'active':'')} onClick={()=>ask()}><Icon as={Sparkles}/><span>Ask SalesPlay</span><span className="ai-label">AI</span></button>
   <button className="nav-label research-toggle" onClick={()=>setResearch(!research)} aria-expanded={research}>ACCOUNT RESEARCH<Icon as={research?ChevronDown:ChevronRight} size={14}/></button>
   {research&&<div>{navLink('Company brief',Building2,'overview')}<button className={'nav-link library-toggle '+(['documents','document','investor','earnings'].includes(view)?'active':'')} aria-expanded={library} aria-controls="library-navigation" onClick={()=>setLibrary(!library)}><FileText size={18}/><span>Research library</span>{library?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button>{library&&<div id="library-navigation">{navLink('All documents',null,'documents',true)}{navLink('Investor deck',null,'investor',true)}{navLink('Earnings call',null,'earnings',true)}</div>}{navLink('Financials',ChartNoAxesCombined,'financials')}{navLink('Competition',Globe,'competitors')}</div>}
  </nav>
 </>}
  <div className="sidebar-bottom"><button className="collapse-navigation" onClick={()=>setSidebar(false)} aria-label="Collapse navigation" aria-expanded="true" aria-controls="workspace-navigation"><PanelLeftClose size={17}/><span>Collapse navigation</span></button><div className="seller"><span>SELLING AS</span><strong>LANXESS <span>Aktiengesellschaft</span></strong></div><div className="profile"><span className="avatar">AJ</span><div><strong>Ankur Jain</strong><span>Sales workspace</span></div><LocalLink className="icon-button" aria-label="SalesPlay help" to={paths.help} go={go}><Icon as={Info}/></LocalLink></div></div>
 </aside>
 {!sidebar&&<nav className="compact-rail" aria-label="Compact navigation"><button className="icon-button compact-expand" aria-label="Expand navigation" title="Expand navigation" onClick={()=>setSidebar(true)}><PanelLeft size={20}/></button>{(portfolio?[[Home,'Home',paths.home,'home'],[Clock3,'Recently used',paths.recent,'recent'],[Star,'Favourites',paths.favourites,'favourites'],[Building2,'All accounts',paths.accounts,'accounts']]:[[Building2,'All accounts',paths.accounts,'accounts'],[BriefcaseBusiness,'Opportunities',paths.list,'list'],[Radio,'Signals',paths.signals,'signals'],[Users,'People',paths.contacts,'contacts'],[Sparkles,'Ask SalesPlay',paths.ai,'ai'],[BookOpen,'Company brief',paths.overview,'overview'],[FileText,'Research library',paths.documents,'documents'],[ChartNoAxesCombined,'Financials',paths.financials,'financials'],[Globe,'Competition',paths.competitors,'competitors']]).map(([I,label,to,key])=><LocalLink key={key} className={'compact-link '+(view===key||(key==='list'&&view==='detail')||(key==='contacts'&&['contact','contactsImport'].includes(view))?'active':'')} to={to} go={go} aria-label={label} title={label}><I size={20}/><span>{label}</span></LocalLink>)}</nav>}
 <div className="workspace">
  <div className="account-trail">{!sidebar&&<button className="expand-navigation icon-button" aria-label="Expand navigation" aria-expanded="false" aria-controls="workspace-navigation" onClick={()=>setSidebar(true)}><PanelLeft size={18}/></button>}<nav aria-label="Breadcrumb">{portfolio&&view!=='accountPreview'?<>{view!=='home'&&<><LocalLink to={paths.home} go={go}>Home</LocalLink><ChevronRight size={13}/></>}<span aria-current="page">{pageNames[view]}</span></>:<><LocalLink to={paths.accounts} go={go}>All Accounts</LocalLink><ChevronRight size={13}/>{view==='accountPreview'?<span>{sampleAccount?.name||'Account'}</span>:<LocalLink to={paths.overview} go={go}>3M Company</LocalLink>}<ChevronRight size={13}/><span aria-current="page">{view==='list'?(opportunityScope==='All opportunities'?'Explore':opportunityScope):pageNames[view]||'Page not found'}</span></>}</nav><span className="preview-label">Design preview</span></div>
  <main id="main" className={view==='ai'?'ai-main':view==='detail'?'main opportunity-detail':'main'}>
  {view==='list'&&<CombinedConcepts variant={10} primary externalScope={opportunityScope} navigationKey={opportunityNavigation} onScopeChange={scope=>go(opportunityUrl(scope))} records={records} onRecordsChange={setRecords} bookmarks={bookmarks} onBookmarksChange={setBookmarks} onNavigate={go}/>}
  {view==='detail'&&<>
   <div className="detail-top"><LocalLink className="text-button muted" to={paths.list} go={go}><ArrowLeft size={16}/>Back to opportunities</LocalLink><div className="detail-tools"><div className="opportunity-decision-actions">{current.status==='review'?<><button className="button primary" onClick={()=>changeStatus(current.id,'accepted')}><Check size={16}/>Accept opportunity</button><button className="button" onClick={()=>changeStatus(current.id,'rejected')}>Reject</button></>:<><span className={'status-badge '+current.status}>{statusLabels[current.status]}</span><button className="button" onClick={()=>changeStatus(current.id,'review')}><RotateCcw size={15}/>Return to review</button></>}</div><button className="icon-button" aria-label={bookmarks.includes(current.id)?'Remove opportunity bookmark':'Bookmark opportunity'} aria-pressed={bookmarks.includes(current.id)} onClick={()=>toggleBookmark(current.id)}><Bookmark size={18} fill={bookmarks.includes(current.id)?'currentColor':'none'}/></button><button className="icon-button" aria-label="Copy opportunity" onClick={()=>copy(current.title+'\n\n'+current.goal)}><Copy size={18}/></button><button className="icon-button" aria-label="Download opportunity as text" onClick={download}><Download size={18}/></button></div></div>
   <header className="detail-heading"><div className="detail-title-row"><h1>{current.title}</h1></div><div className="detail-status"><Evidence value={current.evidence}/><span className={'status-badge '+current.status}>{statusLabels[current.status]}</span><LocalLink className="text-button" to={paths.contacts+'?opportunity='+current.id} go={go}><Users size={16}/>{current.contacts} linked people<ArrowUpRight size={14}/></LocalLink></div><dl className="battle-context"><div><dt>3M business unit</dt><dd>{current.bu}</dd></div>{current.seller&&<div><dt>LANXESS business unit</dt><dd>{current.seller}</dd></div>}{current.region&&<div><dt>Country / region</dt><dd>{current.region}</dd></div>}<div><dt>Mapped offerings</dt><dd>{current.products.join(' / ')}</dd></div></dl></header>
   <div className="detail-nav"><nav className="tabs" aria-label="Opportunity detail">{['Overview','Evidence','Conversation kit'].map(t=><LocalLink key={t} className={detailTab===t?'selected':''} aria-current={detailTab===t?'page':undefined} to={paths.list+'/'+current.id+(t==='Overview'?'':t==='Evidence'?'/evidence':'/conversation-kit')} go={go}>{t}{t==='Evidence'&&current.evidenceItems&&<span>{current.evidenceItems.length}</span>}</LocalLink>)}</nav><button className="button primary" onClick={()=>ask(current)}><Sparkles size={16}/>Ask SalesPlay<ArrowUpRight size={15}/></button></div>
   <div className="detail-layout"><div className="detail-body">
    {detailTab==='Overview'&&<><section className="goal-section"><div className="section-heading"><Icon as={BriefcaseBusiness}/><h2>Your goal</h2></div><p>{current.goal}</p></section>
    {current.evidenceItems&&<section><div className="section-heading"><Icon as={Radio}/><h2>Why call now</h2></div>{current.evidenceItems.map((item,i)=><div key={item.title} className="evidence-item"><FileText className="evidence-source-icon" size={18}/><div><h3>{item.title}</h3><p>{item.text}</p><a className="source-link" href={item.url} target="_blank" rel="noreferrer"><Icon as={FileText} size={13}/>{item.source}<Icon as={ArrowUpRight} size={12}/></a></div></div>)}</section>}
    {current.fit&&<section><div className="section-heading"><Icon as={Building2}/><h2>What this means for you</h2></div>{current.fit.map(([name,text])=><details className="fit-details" key={name}><summary>{name}<Icon as={ChevronDown} size={16}/></summary><p>{text}</p></details>)}</section>}
    {!current.evidenceItems&&<div className="sample-notice"><Icon as={BookOpen}/><div><h3>Original opportunity and goal</h3><p>The detailed battle card was not captured for this opportunity. Browse the available account documents below, or explore its captured context with AI.</p><a href={paths.documents} className="text-button">Explore captured documents<Icon as={ArrowUpRight} size={14}/></a></div></div>}
    </>}
    {detailTab==='Evidence'&&(current.evidenceItems?<><h2 className="tab-title">The evidence behind this opportunity</h2><p className="muted">Review the original sources before deciding whether to pursue.</p>{current.evidenceItems.map((item,i)=><div className="source-document" key={item.title}><span className="file-icon"><Icon as={FileText} size={24}/></span><div><span className="source-index">Source {i+1}</span><h3>{item.source}</h3><p>{item.text}</p><a className="text-button" target="_blank" rel="noreferrer" href={item.url}>Read original source<Icon as={ArrowUpRight} size={14}/></a></div></div>)}</>:<div className="empty-state"><Icon as={FileText} size={30}/><h2>Evidence not captured</h2><p>Individual source links for this opportunity were not included in the captured sample. The local document library contains the available account material.</p><a className="button" href={paths.documents}>Explore documents<Icon as={ArrowUpRight} size={15}/></a></div>)}
    {detailTab==='Conversation kit'&&(current.script?<><section><div className="section-heading"><Icon as={MessageSquare}/><h2>Say this</h2><button className="icon-button" aria-label="Copy conversation opener" onClick={()=>copy(current.script)}><Icon as={Copy} size={16}/></button></div><blockquote>{current.script}</blockquote></section><section><div className="section-heading"><Icon as={CheckCheck}/><h2>Get these three answers</h2></div><ol className="question-list">{current.questions.map(q=><li key={q}>{q}</li>)}</ol></section><section><h2>If you hear this, do this</h2>{current.responses.map(([a,b])=><details className="response-details" key={a}><summary>{a}</summary><p>{b}</p></details>)}</section></>:<div className="empty-state"><Icon as={MessageSquare} size={30}/><h2>Conversation kit not captured</h2><p>This opportunity’s full sales kit is not included in this preview. Use the captured account material to explore the new reading experience.</p><a className="button" href={paths.documents}>Explore documents<Icon as={ArrowUpRight} size={15}/></a></div>)}
   </div><aside className="detail-aside">   <div className="people-preview"><div className="section-heading"><h3>People to start with</h3><span>{current.contacts}</span></div>{current.people?current.people.map(p=><button className="person" key={p.name} onClick={()=>go(paths.contacts+'/'+slug(p.name))}><span className="avatar">{p.initials}</span><span><strong>{p.name}</strong><small>{p.title}</small></span></button>):<p className="muted">{current.contacts} linked contacts in the account.</p>}<button className="text-button" onClick={()=>go(paths.contacts+'?opportunity='+current.id)}>View people<Icon as={ArrowRight} size={14}/></button></div><div className="decision-box"><h3>Your next move</h3><p>{current.next||current.goal}</p>{current.outcome&&<><span className="small-label">DESIRED OUTCOME</span><p>{current.outcome}</p></>}{current.status==='review'?<><button className="button primary full" onClick={()=>changeStatus(current.id,'accepted')}><Icon as={Check} size={16}/>Accept opportunity</button><button className="button full" onClick={()=>changeStatus(current.id,'rejected')}>Reject opportunity</button></>:<button className="button full" onClick={()=>changeStatus(current.id,'review')}><Icon as={RotateCcw} size={15}/>Return to review</button>}<span className="local-note">Preview only · No live records changed</span></div>
   {current.proceed&&<div className="qualification"><h3><Icon as={ShieldCheck} size={17}/>Before you proceed</h3><p>{current.proceed}</p><details><summary>When to stop or change the play</summary><p>{current.stop}</p></details></div>}

   </aside></div>
  </>}
  {view==='ai'&&<div className="ai-workspace">
   <header className="ai-header"><div><span className="ai-symbol"><Icon as={Sparkles} size={22}/></span><div><h1>Ask SalesPlay</h1><p>Your account intelligence, in conversation.</p></div></div><div className="ai-header-actions"><button className="button history-toggle" aria-expanded={historyOpen} aria-controls="ai-history-panel" onClick={()=>setHistoryOpen(!historyOpen)}><Clock3 size={17}/><span>Recent interactions</span>{chats.sessions.length>0&&<span className="history-count">{chats.sessions.length}</span>}</button><button className="button" onClick={newChat}><Plus size={16}/><span>New conversation</span></button></div></header>
   <div className={"ai-grid "+(historyOpen?"history-open":"")}><div className="conversation"><div className="missing-chat" hidden={!route.params.has('chat')||!!chats.active} role="status">This conversation is not saved in this browser. Start a new question below.</div><div className="conversation-scroll">
    {aiContext&&<button className="return-context" onClick={()=>openDetail(aiContext)}><Icon as={ArrowLeft} size={14}/>Back to opportunity</button>}
    {!messages.length?<div className="ai-welcome"><div className="welcome-symbol"><Icon as={Sparkles} size={28}/></div><h2>{entityContext?.item?'Put your context to work.':aiContext?'Find the right way in.':'Where should we look next?'}</h2><p>{entityContext?.item?'Explore '+(entityContext.item.name||entityContext.item.title)+' in the context of your 3M account.':aiContext?'Explore the evidence, validate the fit, and prepare a more relevant conversation.':'Explore opportunities at 3M through the lens of LANXESS. Start with a question, or take one of these paths.'}</p><div className="suggestions">{(entityContext?.item?[["Explore this context",'Help me explore '+(entityContext.item.name||entityContext.item.title)+'.',Sparkles],["Prepare my next step",'Help me prepare a conversation using this context.',MessageSquare]]:aiContext?[['Evaluate this opportunity','What should I validate before pursuing this opportunity?',ShieldCheck],['Find the right people','Who should I contact for this opportunity?',Users],['Prepare a conversation','Help me prepare an opening conversation.',MessageSquare]]:[['Explore the opportunity queue','Show me the opportunities available for 3M.',BriefcaseBusiness],['Start with stronger evidence','Which opportunities have medium evidence?',ShieldCheck],['Find an entry point','Who should I contact for the New Ulm opportunity?',Users]]).map(([title,prompt,I])=><button key={title} onClick={()=>send(prompt)}><Icon as={I} size={20}/><span><strong>{title}</strong><small>{prompt}</small></span><Icon as={ArrowUpRight} size={16}/></button>)}</div></div>:messages.map((m,i)=>m.role==='user'?<div className="user-message" key={i}><span className="small-avatar">AJ</span><p>{m.text}</p></div>:<div className="assistant-message" key={i}><div className="assistant-byline"><Icon as={Sparkles} size={17}/><strong>SalesPlay</strong><span>Demonstration</span></div><AIResponse message={{...m,context:aiContext,entity:entityContext}} records={capturedRecords}/><div className="answer-actions"><span>Based on the inspected account sample</span></div></div>)}
    {busy&&<div className="thinking" role="status"><Icon as={Sparkles} size={17}/>Preparing sample response<span>•••</span></div>}<div ref={chatBottom}/>
   </div><form className="composer" onSubmit={e=>{e.preventDefault();send()}}><div className="composer-context">{entityContext?.item&&<span className="selected-context"><Icon as={entityContext.type==='contact'?Users:FileText} size={13}/>{entityContext.item.name||entityContext.item.title}<button type="button" aria-label="Remove selected context" onClick={()=>go(paths.ai)}><X size={12}/></button></span>}<span><Building2 size={13}/>3M Company</span>{aiContext&&<span className="selected-context"><BriefcaseBusiness size={13}/><span>{aiContext.short}</span><button type="button" aria-label="Remove opportunity context" onClick={()=>go(paths.ai)}><X size={12}/></button></span>}</div><textarea ref={composerRef} aria-label="Message SalesPlay" placeholder={entityContext?.item?'Ask about this '+entityContext.type+'…':aiContext?'Ask about this opportunity…':'Ask about opportunities at 3M…'} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><div className="composer-bottom"><button type="button" className="text-button muted" onClick={()=>setScopeOpen(!scopeOpen)}><Icon as={Paperclip} size={15}/>Choose opportunity context</button><button type="submit" className="send-button" disabled={!draft.trim()||busy} aria-label="Send message"><Icon as={ArrowUp} size={20}/></button></div>{scopeOpen&&<div className="context-picker"><div className="popover-title"><strong>Select an opportunity</strong><button type="button" className="icon-button" aria-label="Close opportunity selector" onClick={()=>setScopeOpen(false)}><X size={16}/></button></div>{capturedRecords.map(o=><button type="button" key={o.id} onClick={()=>{go(paths.ai+'?opportunity='+o.id);setScopeOpen(false)}}>{o.short}<ChevronRight size={14}/></button>)}</div>}</form><p className="ai-disclaimer">Interactive design preview. Responses are scripted; the live assistant is not connected.</p></div>
   <aside className="ai-history-panel" id="ai-history-panel"><details className="working-context"><summary><Building2 size={17}/><span>Working context<strong>3M Company</strong></span><ChevronDown size={15}/></summary><div><p>Selling as LANXESS Aktiengesellschaft</p>{entityContext?.item?<LocalLink to={(entityContext.type==='contact'?paths.contacts:paths.documents)+'/'+entityContext.item.id} go={go}>{entityContext.item.name||entityContext.item.title}<ArrowUpRight size={14}/></LocalLink>:aiContext?<LocalLink to={paths.list+'/'+aiContext.id} go={go}>{aiContext.short}<ArrowUpRight size={14}/></LocalLink>:<p>Account-wide exploration</p>}</div></details><ConversationHistory sessions={chats.sessions} activeId={chats.active?.id} storageError={chats.storageError} go={to=>{setDraft('');setHistoryOpen(false);go(to)}}/></aside></div>

  </div>}
  {view==='home'?<HomeWorkspace go={go} records={capturedRecords} contacts={contactRecords} preferences={preferences} sessions={chats.sessions} recentWork={recentWork} changeStatus={changeStatus} ask={ask}/>:portfolio&&<AccountDirectory route={route} go={go} preferences={preferences}/>}
  {!portfolio&&!['list','detail','ai'].includes(view)&&<WorkspacePages key={route.path} route={route} go={go} askEntity={askEntity} ask={ask} openDetail={openDetail} records={capturedRecords} savedContacts={savedContacts} setSavedContacts={setSavedContacts} contactRecords={contactRecords} onImport={importContacts}/>}
  </main>
 </div>
 {contactPanel&&<div className="drawer-backdrop" onClick={()=>setContactPanel(null)}><section className="contact-drawer" ref={drawerRef} role="dialog" aria-modal="true" aria-label="Opportunity contacts" onClick={e=>e.stopPropagation()}><div className="drawer-heading"><div><h2>People behind the opportunity</h2><p>{contactPanel.contacts} linked contacts</p></div><button className="icon-button" aria-label="Close contacts" onClick={()=>setContactPanel(null)} autoFocus><Icon as={X}/></button></div><p className="drawer-opportunity">{contactPanel.title}</p>{contactPanel.people?<>{contactPanel.people.map(p=><div className="contact-card" key={p.name}><span className="avatar">{p.initials}</span><div><h3>{p.name}</h3><p>{p.title}</p><a className="text-button" href={p.url} target="_blank" rel="noreferrer">LinkedIn<ArrowUpRight size={13}/></a></div></div>)}<p className="local-note">Showing 3 contacts observed in the original battle card.</p></>:<p className="muted">Contact details for this opportunity are available in the existing SalesPlay account.</p>}<a href={paths.contacts+'?opportunity='+contactPanel.id} className="button full">Open people directory<ArrowUpRight size={16}/></a><button className="button primary full" onClick={()=>{ask(contactPanel,'Who should I contact for this opportunity?');setContactPanel(null)}}><Sparkles size={16}/>Find the right people</button></section></div>}
 {toast&&<div className="toast" role="status"><Icon as={Check} size={17}/><span>{toast.message}</span>{toast.undo&&<button onClick={()=>{toast.undo();setToast(null)}}>Undo</button>}<button aria-label="Dismiss notification" onClick={()=>setToast(null)}><X size={14}/></button></div>}
 </div>
}
function ResponseLink({to,children,className}){
 return <a href={to} target="_blank" rel="noopener noreferrer" className={className} title="Opens in a new tab">{children}<ArrowUpRight size={16} aria-hidden="true"/><span className="visually-hidden"> (opens in a new tab)</span></a>;
}
function AIResponse({message,records}){
 if(message.entity?.item){const {type,item}=message.entity;return <><h3>{type==='contact'?'Bring the person and the opportunity together.':'Start with the source.'}</h3><p>{type==='contact'?item.name+' is listed as '+item.title+' at 3M. Confirm their ownership and remit before outreach.':item.title+' · '+item.date+'. The captured document is available in your local workspace.'}</p><p>This sample demonstrates selected {type} context. The live assistant is not connected, so no new research or generated recommendation is being presented.</p><ResponseLink className="button" to={(type==='contact'?paths.contacts:paths.documents)+'/'+item.id}>Review {type}</ResponseLink></>}
 let text=message.text.toLowerCase(),o=message.context;
 if(/who|people|contact/.test(text)){let p=o||records[0];return <><h3>Start by finding the formulation owner.</h3><p>{p.people?'The existing battle card lists these people as starting contacts. Confirm their connection to the New Ulm formulation before treating them as the owner.':'The account links '+p.contacts+' contacts to this opportunity. Open the original battle card to review their roles.'}</p>{p.people&&<div className="answer-people">{p.people.map(p=><div key={p.name}><span className="avatar">{p.initials}</span><span><strong>{p.name}</strong><small>{p.title}</small></span></div>)}</div>}<ResponseLink className="button" to={paths.contacts+'?opportunity='+p.id}>Review linked contacts</ResponseLink></>}
 if(/validat|pressure|evidence|pursu/.test(text)&&o){return <><h3>There is a reason to call. Product fit still needs proof.</h3><p>{o.goal}</p>{o.questions?<><p className="response-lead">Use the battle card’s three qualification questions:</p><ol>{o.questions.map(q=><li key={q}>{q}</li>)}</ol><div className="answer-caveat"><ShieldCheck size={19}/><p>{o.stop}</p></div><ResponseLink className="source-link" to={o.evidenceItems[2].url}><FileText size={14}/>3M cable-accessory portfolio</ResponseLink></>:<p>Detailed evidence for this opportunity remains in the live account.</p>}<ResponseLink className="text-button" to={paths.list+'/'+o.id}>Open battle card</ResponseLink></>}
 if(/opening|conversation|prepare/.test(text)&&o?.script){return <><h3>Lead with the production signal, then qualify the chemistry.</h3><p>This opening comes from the existing battle card:</p><blockquote>{o.script}</blockquote><p className="response-lead">Your desired outcome</p><p>{o.outcome}</p><ResponseLink className="text-button" to={paths.list+'/'+o.id+'/conversation-kit'}>Review the complete conversation kit</ResponseLink></>}
 if(/opportunit|medium|queue/.test(text)&&!o){let list=records.filter(o=>o.status==='review'&&(!/medium|stronger/.test(text)||o.evidence==='Medium'));return <><h3>{/medium|stronger/.test(text)?list.length+' '+(list.length===1?'opportunity has':'opportunities have')+' medium evidence.':'Start with the opportunities already identified.'}</h3><p>These are the inspected opportunities in this preview. Evidence labels reflect the existing account; they are not predictions of success.</p><div className="answer-opportunities">{list.map(o=><ResponseLink key={o.id} to={paths.list+'/'+o.id}><span><strong>{o.title}</strong><small>{o.bu} · {o.contacts} contacts</small></span></ResponseLink>)}</div></>}
 return <><h3>This question is ready for the live assistant.</h3><p>This prototype demonstrates the conversation experience without calling the production AI. Your selected context is {o?o.title:'3M Company, selling as LANXESS'}.</p><p>Try a sample prompt about {o?'validating this opportunity or its contacts':'the opportunity queue or medium evidence'} to explore a response grounded in the reviewed content.</p></>
}
createRoot(document.getElementById('root')).render(location.pathname==='/design-options'?<OpportunityConcepts/>:<App/>);
