import React,{useState} from 'react';
import {Upload,Search,ArrowLeft,ArrowRight,ArrowUpRight,Users,Building2,MapPin,Bookmark,Sparkles,BriefcaseBusiness} from 'lucide-react';
import {Avatar,LocalLink} from './WorkspacePages';
import {paths} from './routing';
export default function PeopleWorkspace({route,go,contacts,records,savedContacts,setSavedContacts,askEntity,ask}){
 const [query,setQuery]=useState(''),[source,setSource]=useState(route.params.get('source')==='uploaded'?'Uploaded':'All people'),[role,setRole]=useState('All roles'),[saved,setSaved]=useState(false);
 const person=contacts.find(p=>p.id===route.id);
 const [opportunityQuery,setOpportunityQuery]=useState(person?.keywords||'');
 const toggle=p=>setSavedContacts(old=>old.includes(p.id)?old.filter(id=>id!==p.id):[...old,p.id]);
 const linkedTo=p=>records.filter(o=>o.people?.some(c=>c.name===p.name)&&!p.imported);
 function opportunityCard(o,linked){return <article className="person-opportunity" key={o.id}><div className="person-opp-meta"><span>{linked?'Verified in captured battle card':'Search result · Link not verified'}</span><span>{o.evidence} evidence</span></div><LocalLink className="person-opp-title" to={paths.list+'/'+o.id} go={go}>{o.title}<ArrowUpRight size={17}/></LocalLink><p>{o.goal}</p><dl><div><dt>3M business unit</dt><dd>{o.bu}</dd></div><div><dt>Mapped offerings</dt><dd>{o.products.join(' / ')}</dd></div></dl>{o.evidenceItems&&<details><summary>Evidence and qualification</summary><p>{o.evidenceItems[0].text}</p><p><strong>Proceed if: </strong>{o.proceed}</p><p><strong>Stop if: </strong>{o.stop}</p></details>}<div className="person-opp-actions"><LocalLink to={paths.list+'/'+o.id} go={go} className="text-button">Open full opportunity<ArrowRight size={15}/></LocalLink><button className="text-button" onClick={()=>ask(o,'What should I validate before pursuing this opportunity?')}><Sparkles size={15}/>Evaluate opportunity</button></div></article>}
 if(route.view==='contact'){
 if(!person)return <div className="empty-state"><h1>Contact not found</h1><p>Uploaded contacts are available only in the browser where they were imported.</p><LocalLink className="button" go={go} to={paths.contacts}>All people</LocalLink></div>;
 const linked=linkedTo(person);const found=records.filter(o=>[o.title,o.goal,o.bu,...o.products].join(' ').toLowerCase().includes(opportunityQuery.trim().toLowerCase()));
 return <><LocalLink className="text-button back-link" to={paths.contacts} go={go}><ArrowLeft size={16}/>All people</LocalLink><div className="person-profile"><Avatar person={person}/><div><h1>{person.name}</h1><p>{person.title}</p><span><Building2 size={15}/>3M Company <MapPin size={15}/>{person.location}{person.imported&&<span className="uploaded-label">Uploaded contact</span>}</span></div><button className="button" onClick={()=>toggle(person)} aria-pressed={savedContacts.includes(person.id)}><Bookmark size={16}/>{savedContacts.includes(person.id)?'Saved':'Save contact'}</button></div><div className="person-detail-layout"><div><section className="person-opportunities"><div className="section-heading"><h2>Linked opportunities</h2><span>{linked.length} captured</span></div>{linked.length?linked.map(o=>opportunityCard(o,true)):<p className="availability-note">{person.imported?'No verified opportunities are linked to this uploaded contact yet.':person.opportunities+' links are reported in the original account, but their details were not captured for this person.'}</p>}</section><section className="person-opportunity-search"><h2>Search opportunities for {person.name.split(' ')[0]}</h2><p>Explore captured account opportunities by product, business unit, or keyword. Search results do not establish this person’s ownership.</p><label className="search-field"><Search size={17}/><input aria-label="Search opportunities for this contact" placeholder="Try cable, coatings, MESAMOLL…" value={opportunityQuery} onChange={e=>setOpportunityQuery(e.target.value)}/></label><div className="person-search-count" role="status">{found.length} of {records.length} captured opportunities</div>{found.map(o=>opportunityCard(o,linked.some(x=>x.id===o.id)))}{!found.length&&<div className="empty-state"><h3>No matching opportunities</h3><p>Try a broader product or business-unit keyword.</p><button className="button" onClick={()=>setOpportunityQuery('')}>Show all captured opportunities</button></div>}</section></div><aside className="profile-aside"><h2>Contact details</h2><dl><dt>Company</dt><dd>3M Company</dd><dt>Location</dt><dd>{person.location}</dd><dt>Email</dt><dd>{person.email?<a href={'mailto:'+person.email}>{person.email}</a>:'Not provided'}</dd>{person.keywords&&<><dt>Opportunity keywords</dt><dd>{person.keywords}</dd></>}</dl>{person.url&&<a className="button full" href={person.url} target="_blank" rel="noreferrer">LinkedIn profile<ArrowUpRight size={15}/></a>}<button className="button primary full" onClick={()=>askEntity('contact',person.id,'Help me prepare a conversation with '+person.name+'.')}><Sparkles size={16}/>Prepare a conversation</button><p className="source-note">{person.imported?'Uploaded by you · Saved in this browser.':'Captured profile · Confirm role and ownership before outreach.'}</p></aside></div></>;
 }
 const opportunity=records.find(o=>o.id===route.params.get('opportunity'));
 const pool=opportunity?contacts.filter(p=>linkedTo(p).some(o=>o.id===opportunity.id)):contacts;
 const shown=pool.filter(p=>(source!=='Uploaded'||p.imported)&&(!saved||savedContacts.includes(p.id))&&(role==='All roles'||p.title.toLowerCase().includes(role.toLowerCase()))&&[p.name,p.title,p.location,p.email,p.keywords].filter(Boolean).join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><div className="page-heading"><div><h1>People at 3M</h1><p>Bring your relationships together. Find the next opportunity.</p></div><LocalLink className="button primary" to={paths.contactsImport} go={go}><Upload size={17}/>Upload contacts</LocalLink></div>{opportunity&&<div className="scope-strip"><BriefcaseBusiness size={16}/><span>Linked to {opportunity.short}</span><LocalLink to={paths.contacts} go={go}>Show all people</LocalLink></div>}<div className="people-view-tabs"><button className={source==='All people'?'selected':''} onClick={()=>setSource('All people')}>All people <span>{contacts.length}</span></button><button className={source==='Uploaded'?'selected':''} onClick={()=>setSource('Uploaded')}>Uploaded <span>{contacts.filter(p=>p.imported).length}</span></button></div><div className="toolbar"><label className="search-field"><Search size={17}/><input aria-label="Search people" placeholder="Search people, roles, or keywords…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="select-field">Role<select value={role} onChange={e=>setRole(e.target.value)}>{['All roles','Operations','Supply Chain','Quality','R&D','Manufacturing'].map(r=><option key={r}>{r}</option>)}</select></label><button className="button" aria-pressed={saved} onClick={()=>setSaved(!saved)}><Bookmark size={16}/>Saved</button></div><div className="people-directory">{shown.map(p=><article className="people-directory-row" key={p.id}><LocalLink className="contact-identity" to={paths.contacts+'/'+p.id} go={go}><Avatar person={p}/><span><strong>{p.name}</strong><small>{p.title}</small>{p.imported&&<small className="uploaded-label">Uploaded</small>}</span></LocalLink><span className="people-location">{p.location}</span><LocalLink className="people-opportunity-link" to={paths.contacts+'/'+p.id} go={go}>{linkedTo(p).length?linkedTo(p).length+' captured opportunity':'Find opportunities'}<ArrowRight size={15}/></LocalLink><button className="icon-button" aria-label={(savedContacts.includes(p.id)?'Unsave ':'Save ')+p.name} aria-pressed={savedContacts.includes(p.id)} onClick={()=>toggle(p)}><Bookmark size={17} fill={savedContacts.includes(p.id)?'currentColor':'none'}/></button></article>)}</div>{!shown.length&&<div className="empty-state"><Users size={26}/><h2>{source==='Uploaded'&&!contacts.some(p=>p.imported)?'Bring your contacts into SalesPlay':'No matching people'}</h2><p>{source==='Uploaded'?'Upload a CSV, then open a contact to search opportunities.':'Try another search or clear the filters.'}</p>{source==='Uploaded'?<LocalLink className="button" to={paths.contactsImport} go={go}>Upload contacts</LocalLink>:<button className="button" onClick={()=>{setQuery('');setRole('All roles');setSaved(false);go(paths.contacts)}}>Reset search</button>}</div>}<p className="source-note">{shown.length} {shown.length===1?'profile':'profiles'} shown · Captured research and your browser-local uploads</p></>;
}
