import React,{useState} from 'react';
import {ArrowRight,ArrowLeft,ArrowUpRight,Search,Users,Sparkles,Bookmark,MapPin,Mail,BriefcaseBusiness,FileText,Building2,Radio,Download,Globe,Check,ChevronRight} from 'lucide-react';
import research from './research.json';
import PeopleWorkspace from './PeopleWorkspace';
import ContactImport from './ContactImport.jsx';
import {people,opportunities} from './data';
import {paths,slug,follow} from './routing';
export const contacts=[...research.contacts,...people.filter(p=>!research.contacts.some(c=>c.name===p.name)).map(p=>({...p,id:slug(p.name),location:'Location not captured',opportunities:1}))].map(p=>({...p,...people.find(x=>x.name===p.name)}));
export const documents=research.documents;
export function LocalLink({to,go,children,...props}){return <a href={to} onClick={e=>follow(e,go,to)} {...props}>{children}</a>}
export function Avatar({person}){return <span className={'avatar portrait portrait-'+(person.initials.charCodeAt(0)%3)}>{person.initials}</span>}
export function PeoplePanel({go}){return <aside className="people-desk"><div className="desk-heading"><h2>People to know</h2></div><p className="desk-intro">Starting points for the New Ulm opportunity.</p>{people.map(p=><div className="desk-person" key={p.name}><LocalLink to={paths.contacts+'/'+slug(p.name)} go={go}><Avatar person={p}/><span><strong>{p.name}</strong><small>{p.title}</small></span></LocalLink></div>)}<LocalLink className="text-button desk-all" to={paths.contacts} go={go}>View all people <ArrowRight size={16}/></LocalLink><p className="desk-note">Confirm each person’s role before outreach.</p></aside>}
function signalDate(value){const [day,month,year]=value.split('/');return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(Number(year),Number(month)-1,Number(day))))}
const titles={contacts:['People at 3M','Find the right person for your next conversation.'],overview:['Company brief','The company, its priorities, and your way in.'],signals:['Signals','Company updates that could inform your next move.'],documents:['Research library','Explore the sources behind your account intelligence.'],investor:['Investor deck','Read the presentation in the context of your account.'],earnings:['Earnings call','Management’s perspective, ready to explore.'],financials:['Financials','The numbers behind the account.'],competitors:['Competition','Compare the account with its competitive landscape.'],accounts:['Your accounts','Find your next conversation.'],help:['Working with SalesPlay','A guide to this interactive design preview.']};
function Heading({view,action}){const t=titles[view]||['Page not found','This address is not part of the account workspace.'];return <div className="page-heading"><div><h1>{t[0]}</h1><p>{t[1]}</p></div>{action}</div>}
function SearchField({value,onChange,placeholder}){return <label className="search-field"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SourceNote({children}){return <p className="source-note"><FileText size={14}/>{children||'Captured from the existing SalesPlay account · Design preview'}</p>}
function DataTable({rows}){return <div className="table-scroll"><table className="research-table"><thead><tr>{rows[0].map((h,i)=><th key={i} scope="col">{h||'Metric'}</th>)}</tr></thead><tbody>{rows.slice(1).map((r,i)=><tr key={i}>{r.map((c,j)=>j===0?<th key={j} scope="row">{c}</th>:<td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
export default function WorkspacePages({route,go,askEntity,ask,openDetail,records,savedContacts,setSavedContacts,contactRecords=contacts,onImport}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All roles'),[savedOnly,setSavedOnly]=useState(false),[docQuery,setDocQuery]=useState(''),[signalCategory,setSignalCategory]=useState('All categories');
 const {view,id}=route;
 const toggle=p=>setSavedContacts(prev=>prev.includes(p.id)?prev.filter(x=>x!==p.id):[...prev,p.id]);
 const person=contacts.find(p=>p.id===id);
 function saveText(title,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=slug(title)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 if(view==='contactsImport')return <ContactImport go={go} contacts={contactRecords} onImport={onImport}/>;
 if(view==='contacts'||view==='contact')return <PeopleWorkspace key={route.path} route={route} go={go} contacts={contactRecords} records={records} savedContacts={savedContacts} setSavedContacts={setSavedContacts} askEntity={askEntity} ask={ask}/>;
 if(view==='overview')return <><Heading view={view} action={<button className="button primary" onClick={()=>ask(null,'Help me find opportunities at 3M.')}><Sparkles size={16}/>Explore the account</button>}/><div className="overview-layout compact-overview"><article className="editorial-paper"><div className="company-masthead"><span className="company-logo">3M</span><div><h2>3M Company</h2><p>Industrial conglomerate · Founded 1902 · Saint Paul, Minnesota</p></div></div><div className="overview-copy">{research.overview.split(/\n\n/).map((p,i)=><p key={i}>{p}</p>)}</div><a className="text-button" href="https://www.3m.com" target="_blank" rel="noreferrer">Company website<ArrowUpRight size={14}/></a></article><PeoplePanel go={go} askEntity={askEntity}/></div><section className="research-section"><div className="section-heading"><h2>Revenue by business segment</h2><LocalLink go={go} to={paths.financials} className="text-button">Explore financials<ArrowRight size={15}/></LocalLink></div><DataTable rows={[["Segment","2024 ($ Mn)","2025 ($ Mn)","Change (%)"],["Safety and Industrial","10,961","11,384","3.9"],["Transportation and Electronics","8,380","8,272","−1.3"],["Consumer","4,931","4,920","−0.2"],["Corporate and Other","303","372","22.8"]]}/><SourceNote/></section></>;
 if(['financials','competitors'].includes(view)){const table=view==='financials'?research.financials:research.competitors;const filtered=[table[0],...table.slice(1).filter(r=>r[0].toLowerCase().includes(query.toLowerCase()))];return <><Heading view={view}/><div className="research-summary"><div><h2>{view==='financials'?'Five years of account performance':'3M Company vs. key competitors'}</h2><p>{view==='financials'?'Annual key statistics, 2021–2025.':'Annual figures as shown in the captured comparison. Periods are not labeled in the source view.'}</p></div><button className="button" onClick={()=>saveText(view,table.map(r=>r.join('\t')).join('\n'))}><Download size={16}/>Export table</button></div><div className="toolbar"><SearchField value={query} onChange={setQuery} placeholder={view==='financials'?'Find a financial metric…':'Find a company…'}/><span className="table-unit">USD millions, except EPS</span></div><DataTable rows={filtered}/>{filtered.length===1&&<div className="empty-state"><h2>No matching rows</h2><button className="button" onClick={()=>setQuery('')}>Clear search</button></div>}<SourceNote>Captured SalesPlay figures. Comparison values may use a different reporting period from the financials view.</SourceNote></>}
 if(['documents','document','investor','earnings'].includes(view)){const selected=view==='investor'?documents[1]:view==='earnings'?documents[2]:documents.find(d=>d.id===id);if(selected)return <><LocalLink className="text-button back-link" to={paths.documents} go={go}><ArrowLeft size={15}/>Research library</LocalLink><div className="page-heading"><div><h1>{selected.title}</h1><p>{selected.type} · {selected.date}</p></div><button className="button primary" onClick={()=>askEntity('document',selected.id,'Help me explore '+selected.title+'.')}><Sparkles size={17}/>Ask about this document</button></div><div className="document-workspace"><aside className="document-index"><h2>In this account</h2>{documents.map(d=><LocalLink key={d.id} className={d.id===selected.id?'selected':''} to={paths.documents+'/'+d.id} go={go}><FileText size={17}/><span><strong>{d.title}</strong><small>{d.date}</small></span></LocalLink>)}<button className="button full" onClick={()=>saveText(selected.title,selected.text)}><Download size={16}/>Download captured text</button><p>Text captured from the existing document reader. Original layout and charts are not reproduced.</p></aside><article className="document-paper"><div className="document-paper-heading"><FileText size={19}/><span>Captured document text</span></div>{selected.text.split(/\n\n+/).map((p,i)=><p key={i}>{p}</p>)}</article></div></>;return <><Heading view={view}/><div className="toolbar"><SearchField value={docQuery} onChange={setDocQuery} placeholder="Search captured documents…"/><span className="table-unit">3 captured documents</span></div><div className="document-library">{documents.filter(d=>(d.title+' '+d.type).toLowerCase().includes(docQuery.toLowerCase())).map(d=><LocalLink to={paths.documents+'/'+d.id} go={go} className="document-row" key={d.id}><span className="document-icon"><FileText size={29}/></span><span><small>{d.type}</small><h2>{d.title}</h2><p>{d.date} · 3M Company</p></span><span className="document-read">Read document <ArrowRight size={17}/></span></LocalLink>)}</div>{!documents.some(d=>(d.title+' '+d.type).toLowerCase().includes(docQuery.toLowerCase()))&&<div className="empty-state"><h2>No matching documents</h2><button className="button" onClick={()=>setDocQuery('')}>Clear search</button></div>}<SourceNote>This library contains the three documents captured for this preview, not the full live document archive.</SourceNote></>}
 if(view==='signals'||view==='signal'){const signal=research.signals.find(s=>s.id===id);if(signal)return <><LocalLink className="text-button back-link" to={paths.signals} go={go}><ArrowLeft size={15}/>All signals</LocalLink><article className="signal-reader editorial-paper"><div className="signal-meta"><span>{signal.category}</span><time>{signalDate(signal.date)}</time></div><h1>{signal.title}</h1><p className="signal-body">{signal.body}</p><SourceNote>{signal.source} · Captured in SalesPlay</SourceNote><LocalLink className="button primary" to={paths.list} go={go}>Explore related account opportunities<ArrowRight size={16}/></LocalLink></article></>;const shown=research.signals.filter(s=>(signalCategory==='All categories'||s.category===signalCategory)&&(s.title+' '+s.body).toLowerCase().includes(query.toLowerCase()));return <><Heading view={view}/><div className="toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search signals…"/><label className="select-field">Category<select value={signalCategory} onChange={e=>setSignalCategory(e.target.value)}><option>All categories</option>{[...new Set(research.signals.map(s=>s.category))].map(c=><option key={c}>{c}</option>)}</select></label></div><div className="signals-list">{shown.map(s=><LocalLink className="signal-row" key={s.id} go={go} to={paths.signals+'/'+s.id}><div><div className="signal-row-meta"><span className="signal-category">{s.category}</span><time>{signalDate(s.date)}</time></div><h2>{s.title}</h2><p>{s.body}</p><small>{s.source}</small></div><ArrowUpRight size={18}/></LocalLink>)}</div>{!shown.length&&<div className="empty-state"><h2>No matching account updates</h2><button className="button" onClick={()=>{setQuery('');setSignalCategory('All categories')}}>Reset search</button></div>}<SourceNote>10 updates captured from the original feed · 429 available in the live account</SourceNote></>}
 if(view==='help')return <><Heading view={view}/><div className="editorial-paper help-content"><h2>One account, three ways in</h2><p>Start with an opportunity, a person, or a question. Every account section has its own local URL, and the browser’s Back and Forward controls preserve your navigation.</p><h2>Ask SalesPlay</h2><p>Use the top-bar field from anywhere. Choose Search to find captured opportunities, people, documents, and signals. Choose Ask SalesPlay to take a question into the dedicated AI workspace.</p><h2>About this preview</h2><p>Account content was captured from the existing 3M/LANXESS workspace. Review decisions and saved contacts remain in this browser session. AI responses are scripted demonstrations. No backend API is called and no outreach is sent.</p></div></>;
 return <><Heading view="notfound"/><LocalLink className="button primary" to={paths.list} go={go}>Return to opportunities<ArrowRight size={16}/></LocalLink></>;
}
